export const FETCH_JOB_SUCCESS = 'FETCH_JOB_SUCCESS';
export const FETCH_JOB_FAILURE = 'FETCH_JOB_FAILURE';
export const FETCH_JOB_BEGIN = 'FETCH_JOB_BEGIN';

export const GET_ANALYSIS_SUCCESS = 'GET_ANALYSIS_SUCCESS';
export const GET_ANALYSIS_FAILURE = 'GET_ANALYSIS_FAILURE';
export const GET_ANALYSIS_BEGIN = 'GET_ANALYSIS_BEGIN';

export const POST_JOB_BEGIN = 'POST_JOB_BEGIN';
export const POST_JOB_SUCCESS = 'POST_JOB_SUCESS';
export const POST_JOB_FAILURE = 'POST_JOB_FAILURE';

export const DELETE_JOB_BEGIN = 'DELETE_JOB_BEGIN';
export const DELETE_JOB_SUCCESS = 'DELETE_JOB_SUCCESS';
export const DELETE_JOB_FAILURE = 'DELETE_JOB_FAILURE';

export const EDIT_JOB_BEGIN = 'EDIT_JOB_BEGIN';
export const EDIT_JOB_SUCCESS = 'EDIT_JOB_SUCCESS';
export const EDIT_JOB_FAILURE = 'EDIT_JOB_FAILURE';

export const FETCH_USER_PROFILE_BEGIN = 'FETCH_USER_PROFILE_BEGIN';
export const FETCH_USER_PROFILE_SUCCESS = 'FETCH_USER_PROFILE_SUCCESS';
export const FETCH_USER_PROFILE_FAILURE = 'FETCH_USER_PROFILE_FAILURE';
export const FETCH_USER = 'FETCH_USER';

export const GET_USER_IMAGE_URL = 'GET_USER_IMAGE_URL';

export const GET_DETAIL_JOB = 'GET_DETAIL_JOB';
export const SEARCH_FILTER = 'SEARCH_FILTER';
export const CHANGE_STATE_DETAILPAGE = 'CHANGE_STATE_DETAILPAGE';

export const GET_AUTOCOMPLETEJOB_BEGIN = 'GET_AUTOCOMPLETEJOB_BEGIN';
export const GET_AUTOCOMPLETEJOB_FAILURE = 'GET_AUTOCOMPLETEJOB_FAILURE';
export const GET_AUTOCOMPLETEJOB_SUCCESS = 'GET_AUTOCOMPLETEJOB_SUCCESS';
export const FILTER_AUTOCOMPLETEJOB = 'FILTER_AUTOCOMPLETEJOB';
export const CLEAR_AUTOCOMPLETEJOB = 'CLEAR_AUTOCOMPLETEJOB';

export const POST_IMAGE_BEGIN = 'POST_IMAGE_BEGIN';
export const POST_IMAGE_SUCCESS = 'POST_IMAGE_SUCCESS';

export const AUTHENTICATED = 'AUTHENTICATED';
export const UNAUTHENTICATED = 'UNAUTHENTICATED';
export const AUTHENTICATION_ERROR = 'AUTHENTICATION_ERROR';
